services:

#############################################
# The Code Quality Review Processor service #
#############################################

  review_processor:
    class: Hostnet\HostnetCodeQualityBundle\Lib\ReviewProcessor
    arguments: [@doctrine.orm.entity_manager, @entity_factory, @original_file_retrieval_factory, @command_line_utility, @parser_factory]

##############################
# The Entity Factory service #
##############################

  entity_factory:
    class: Hostnet\HostnetCodeQualityBundle\Lib\EntityFactory
    arguments: [@doctrine.orm.entity_manager]

########################################
# The Original File Retrieval services #
########################################

  original_file_retrieval_factory:
    class: Hostnet\HostnetCodeQualityBundle\Parser\OriginalFileRetriever\OriginalFileRetrievalFactory
    arguments: [%hostnet_code_quality.original_file_retrieval_method%]
    calls:
      - [ addOriginalFileRetrieverInstance, [@original_file_retriever.retrieve_by_cgit] ]

  original_file_retriever.retrieve_by_cgit:
    class: Hostnet\HostnetCodeQualityBundle\Parser\OriginalFileRetriever\RetrieveByCGIT
    arguments: [%hostnet_code_quality.raw_file_url_mask_1%, %hostnet_code_quality.raw_file_url_mask_2%]

####################################
# The Command Line Utility service #
####################################

  command_line_utility:
    class: Hostnet\HostnetCodeQualityBundle\Parser\CommandLineUtility
    arguments: [%hostnet_code_quality.temp_cq_dir_name%]

#######################
# The Parser services #
#######################

  parser_factory:
    class: Hostnet\HostnetCodeQualityBundle\Parser\ParserFactory
    arguments: [%hostnet_code_quality.scm%]
    calls:
      - [ addParserInstance, [@diff_parser.git_diff_parser] ]
      - [ addParserInstance, [@diff_parser.svn_diff_parser] ]
      - [ addParserInstance, [@tool_output_parser.xml.pmd_xml_parser] ]
      - [ addParserInstance, [@tool_output_parser.xml.jslint_xml_parser] ]

  diff_parser.git_diff_parser:
    class: Hostnet\HostnetCodeQualityBundle\Parser\DiffParser\GITDiffParser

  diff_parser.svn_diff_parser:
    class: Hostnet\HostnetCodeQualityBundle\Parser\DiffParser\SVNDiffParser

  tool_output_parser.xml.pmd_xml_parser:
    class: Hostnet\HostnetCodeQualityBundle\Parser\ToolOutputParser\XML\PMDXMLParser
    arguments: [@entity_factory]

  tool_output_parser.xml.jslint_xml_parser:
    class: Hostnet\HostnetCodeQualityBundle\Parser\ToolOutputParser\XML\JSLintXMLParser
    arguments: [@entity_factory]

##########################
# Review Board API Calls #
##########################

  review_board_api_calls:
    class: Hostnet\HostnetCodeQualityBundle\Command\ReviewBoardAPICalls
    arguments: [%hostnet_code_quality.domain%, %hostnet_code_quality.review_board_username%, %hostnet_code_quality.review_board_password%]

#####################
# Feedback Handlers #
#####################

  review_board_feedback_handler:
    class: Hostnet\HostnetCodeQualityBundle\Lib\ReviewBoardFeedbackHandler
