services:

#############################################
# The Code Quality Review Processor service #
#############################################

  review_processor:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Lib\ReviewProcessor
    arguments: [@doctrine.orm.entity_manager, @logger, @entity_factory, @original_file_retrieval_factory, @command_line_utility, @parser_factory]

##############################
# The Entity Factory service #
##############################

  entity_factory:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Lib\EntityFactory
    arguments: [@doctrine.orm.entity_manager]

########################################
# The Original File Retrieval services #
########################################

  original_file_retrieval_factory:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Parser\OriginalFileRetriever\OriginalFileRetrievalFactory
    calls:
      - [ addOriginalFileRetrieverInstance, [@original_file_retriever.retrieve_by_cgit] ]
      - [ addOriginalFileRetrieverInstance, [@original_file_retriever.retrieve_by_review_board] ]

  original_file_retriever.retrieve_by_cgit:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Parser\OriginalFileRetriever\RetrieveByCGIT
    arguments: [%hostnet_code_quality.raw_file_url_mask_1%, %hostnet_code_quality.raw_file_url_mask_2%]

  original_file_retriever.retrieve_by_review_board:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Parser\OriginalFileRetriever\RetrieveByReviewBoard
    arguments: [@review_board_api_calls]

####################################
# The Command Line Utility service #
####################################

  command_line_utility:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Parser\CommandLineUtility
    arguments: [%hostnet_code_quality.temp_cq_dir_name%]

#######################
# The parser services #
#######################

  parser_factory:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Parser\ParserFactory
    arguments: [%hostnet_code_quality.scm%]
    calls:
      - [ addParserInstance, [@diff_parser.git_diff_parser] ]
      - [ addParserInstance, [@diff_parser.svn_diff_parser] ]
      - [ addParserInstance, [@tool_output_parser.xml.pmd_xml_parser] ]
      - [ addParserInstance, [@tool_output_parser.xml.jslint_xml_parser] ]

  diff_parser.git_diff_parser:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Parser\DiffParser\GITDiffParser

  diff_parser.svn_diff_parser:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Parser\DiffParser\SVNDiffParser

  tool_output_parser.xml.pmd_xml_parser:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Parser\ToolOutputParser\XML\PMDXMLParser
    arguments: [@entity_factory]

  tool_output_parser.xml.jslint_xml_parser:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Parser\ToolOutputParser\XML\JSLintXMLParser
    arguments: [@entity_factory]

##############################
# Feedback receiving service #
##############################

  review_board_api_calls:
    class: Hostnet\Bundle\HostnetCodeQualityBundle\Lib\FeedbackReceiver\ReviewBoard\ReviewBoardAPICalls
    arguments: [%hostnet_code_quality.review_board_base_url%, %hostnet_code_quality.review_board_username%, %hostnet_code_quality.review_board_password%, %hostnet_code_quality.review_board_auto_shipit%]
